apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn.fullname" . }}
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
type: Opaque
data:
  ta.key: {{ .Values.openvpn.ta_key | b64enc | quote }}
  ca.crt: {{ .Values.openvpn.ca_crt | b64enc | quote }}
  server.crt: {{ .Values.openvpn.server_crt | b64enc | quote }}
  server.key: {{ .Values.openvpn.server_key | b64enc | quote }}
