apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvpn.fullname" . }}
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if hasKey .Values.service "nodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: UDP
      name: http
  selector:
    {{- include "openvpn.selectorLabels" . | nindent 4 }}
